############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "About Us"

[[main]]
parent = "About Us"
name = "About Han"
url = "/about"
weight = 1

[[main]]
parent = "About Us"
name = "About the Web Developer"
url = "/about/developer1"
weight = 2

[[main]]
parent = "About Us"
name = "About someone"
url = "/about/developer2"
weight = 3

[[main]]
parent = "About Us"
name = "Members"
url = "/authors"
weight = 4

[[main]]
name = "Elements"
url = "/elements"
weight = 3

[[main]]
name = "Projects"
url = "/categories"
weight = 4

[[main]]
weight = 5
name = "Publications"

[[main]]
parent = "Publications"
name = "Blog"
url = "/blog"

[[main]]
parent = "Publications"
name = "Our Publications"
url = "/publications"

[[main]]
parent = "Publications"
name = "Our Book"
url = "/books"

[[main]]
name = "Data Sources"
url = "/data-sources"
weight = 6


# footer menu
[[footer]]
name = "About Us"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
